[package]
name = "selene-lib"
version = "0.20.0"
license = "MPL-2.0"
authors = ["Kampfkarren <kampfkarren@gmail.com>"]
description = "A library for linting Lua code. You probably want selene instead."
categories = ["command-line-utilities"]
keywords = ["lua", "linter", "lua51"]
repository = "https://github.com/Kampfkarren/selene"
edition = "2021"

[dependencies]
codespan = "0.9.5"
codespan-reporting = "0.9.5"
# full_moon = { git = "https://github.com/Kampfkarren/full-moon", branch = "lua-types" }
# full-moon-lua-types = { git = "https://github.com/Kampfkarren/full-moon", branch = "lua-types" }
full_moon.workspace = true
full-moon-lua-types.workspace = true
id-arena = "2.2"
if_chain = "1.0"
lazy_static = "1.4"
mlua = { version = "0.8.3", features = ["luau", "send"] }
once_cell = "1.12.0"
paste = "1.0.9"
profiling = "1.0.6"
rbx_reflection = { version = "3", optional = true }
regex = "1"
serde = "1.0"
serde_yaml = "0.8.24"
toml = "0.5"

[dev-dependencies]
serde_json = "1.0"
pretty_assertions = "0.6"
termcolor = "1.0"

[features]
default = ["roblox"]
force_exhaustive_checks = []
roblox = ["rbx_reflection", "full_moon/roblox", "full-moon-lua-types/luau"]
